# -*- coding: utf-8 -*-
"""Untitled24.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11khI5aGYwKhg-AvAL86J-jfHH--HjerJ
"""

# =============================================================================
# PREDICCIÓN DE CLASIFICADOS A CUARTOS DE FINAL (OCTAVOS -> CUARTOS)
# VERSIÓN OPTIMIZADA (más rápida)
# =============================================================================

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import re
import xgboost as xgb
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import StratifiedKFold, RandomizedSearchCV
from sklearn.metrics import accuracy_score
from collections import defaultdict
import warnings
import joblib  # para guardar/cargar modelos
import os
warnings.filterwarnings('ignore')

print("🏆 PREDICCIÓN DE CLASIFICADOS A CUARTOS DE FINAL (MODELO OPTIMIZADO)")
print("="*80 + "\n")

# ============================================================
# 1. CARGA Y LIMPIEZA DE DATOS
# ============================================================

base_path = '/content/drive/MyDrive/Simulaciones_Mundial/Data'

# Archivos necesarios
cruces_octavos = pd.read_csv(f"{base_path}/Cruces_4tos.csv", sep=',')
datos_historicos = pd.read_csv(f"{base_path}/datos_historicos.csv")
datos_mundial = pd.read_csv(f"{base_path}/datos_mundial.csv")
ranking_fifa = pd.read_csv(f"{base_path}/ranking_fifa.csv")
transfermarkt = pd.read_csv(f"{base_path}/transfermarkt.csv")

print("✅ Archivos cargados correctamente.")

# ============================================================
# 2. LIMPIEZA DE NOMBRES (normalización)
# ============================================================

def clean_name(name):
    name = str(name).strip()
    replacements = {
        'Estados Unidos': 'EE. UU.',
        'USA': 'EE. UU.',
        'Bosnia y Herzegovina': 'Bosnia-Herzegovina',
        'Bosnia': 'Bosnia-Herzegovina',
        'República de Corea': 'Corea del Sur',
        'RI de Irán': 'Irán',
        'Islas de Cabo Verde': 'Cabo Verde',
        'Cabo Verde': 'Cabo Verde',
        "Côte d'Ivoire": 'Costa de Marfil',
        'Congo': 'RD Congo',
        'República Democrática del Congo': 'RD Congo',
        'República del Congo': 'Congo',
        'Chequia': 'República Checa',
        'República Checa': 'República Checa',
    }
    for old, new in replacements.items():
        name = name.replace(old, new)
    return name

if 'País' in ranking_fifa.columns:
    ranking_fifa = ranking_fifa.rename(columns={'País': 'Equipo'})

for df in [datos_historicos, datos_mundial, ranking_fifa, transfermarkt]:
    if 'Equipo' in df.columns:
        df['Equipo'] = df['Equipo'].apply(clean_name)
    if 'Equipo_Local' in df.columns:
        df['Equipo_Local'] = df['Equipo_Local'].apply(clean_name)
        df['Equipo_Visitante'] = df['Equipo_Visitante'].apply(clean_name)

# Limpiar nombres en cruces_octavos
cruces_octavos['Equipo Local'] = cruces_octavos['Equipo Local'].apply(clean_name)
cruces_octavos['Equipo Visitante'] = cruces_octavos['Equipo Visitante'].apply(clean_name)

print("✅ Nombres normalizados.")

# ============================================================
# 3. CONSTRUCCIÓN DEL DATASET DE EQUIPOS (con más características)
# ============================================================

def get_numeric(df):
    return df[['Equipo'] + df.select_dtypes(include=[np.number]).columns.tolist()]

# Unimos las fuentes de datos
stats = (get_numeric(ranking_fifa)
         .merge(get_numeric(transfermarkt), on='Equipo', how='left')
         .merge(get_numeric(datos_mundial), on='Equipo', how='left'))
stats = stats.fillna(0)

# Características derivadas
if 'avg_Goles_total' in stats.columns and 'avg_Posesión_total' in stats.columns:
    stats['ratio_goles_posesion'] = stats['avg_Goles_total'] / (stats['avg_Posesión_total'] + 0.01)
if 'avg_Tarjetas_amarillas_total' in stats.columns and 'avg_Faltas_total' in stats.columns:
    stats['ratio_tarjetas'] = stats['avg_Tarjetas_amarillas_total'] / (stats['avg_Faltas_total'] + 0.01)
if 'avg_Goles_total' in stats.columns and 'avg_Remates_a_puerta_total' in stats.columns:
    stats['eficiencia_gol'] = stats['avg_Goles_total'] / (stats['avg_Remates_a_puerta_total'] + 0.01)
if 'avg_Córneres_total' in stats.columns and 'avg_Posesión_total' in stats.columns:
    stats['ratio_corners'] = stats['avg_Córneres_total'] / (stats['avg_Posesión_total'] + 0.01)

# Verificar que todos los equipos de los cruces estén en stats
equipos_cruces = set(cruces_octavos['Equipo Local']).union(set(cruces_octavos['Equipo Visitante']))
faltantes = [eq for eq in equipos_cruces if eq not in stats['Equipo'].values]
if faltantes:
    print(f"⚠️ Equipos sin estadísticas: {faltantes}. Se añadirán con valores por defecto.")
    for eq in faltantes:
        new_row = {'Equipo': eq}
        for col in stats.columns:
            if col != 'Equipo':
                new_row[col] = 0
        stats = pd.concat([stats, pd.DataFrame([new_row])], ignore_index=True)
    stats = stats.fillna(0)

print("📊 Estadísticas de equipos listas con características mejoradas.")

# ============================================================
# 4. ENTRENAMIENTO DEL MODELO XGBOOST OPTIMIZADO (con guardado)
# ============================================================

# Definir rutas para guardar modelo y scaler
model_path = f"{base_path}/best_model_xgb.pkl"
scaler_path = f"{base_path}/scaler_xgb.pkl"

# Verificar si ya existen modelo y scaler guardados
if os.path.exists(model_path) and os.path.exists(scaler_path):
    print("🔄 Cargando modelo y scaler guardados...")
    best_model = joblib.load(model_path)
    scaler = joblib.load(scaler_path)
    print("✅ Modelo y scaler cargados correctamente.")
else:
    print("🔄 No se encontraron modelo y scaler guardados. Entrenando desde cero...")

    # Preparar datos de entrenamiento
    train_data = []
    for _, row in datos_historicos.iterrows():
        h = row['Equipo_Local']
        a = row['Equipo_Visitante']
        s_h = stats[stats['Equipo'] == h]
        s_a = stats[stats['Equipo'] == a]
        if s_h.empty or s_a.empty:
            continue
        s_h = s_h.iloc[0]
        s_a = s_a.iloc[0]

        match = {}
        for col in stats.select_dtypes(include=[np.number]).columns:
            if col != 'Equipo':
                match[f"{col}_diff"] = s_h[col] - s_a[col]

        # Características derivadas
        if 'ratio_goles_posesion' in stats.columns:
            match['ratio_goles_posesion_diff'] = s_h['ratio_goles_posesion'] - s_a['ratio_goles_posesion']
        if 'ratio_tarjetas' in stats.columns:
            match['ratio_tarjetas_diff'] = s_h['ratio_tarjetas'] - s_a['ratio_tarjetas']
        if 'eficiencia_gol' in stats.columns:
            match['eficiencia_gol_diff'] = s_h['eficiencia_gol'] - s_a['eficiencia_gol']
        if 'ratio_corners' in stats.columns:
            match['ratio_corners_diff'] = s_h['ratio_corners'] - s_a['ratio_corners']

        match['peso_local'] = row.get('Peso_Local', 0.5)

        # Target: 1 = local gana, -1 = visitante gana, 0 = empate
        if row['Goles_Local'] > row['Goles_Visitante']:
            match['target'] = 1
        elif row['Goles_Local'] < row['Goles_Visitante']:
            match['target'] = -1
        else:
            match['target'] = 0

        train_data.append(match)

    df_train = pd.DataFrame(train_data)
    X = df_train.drop(columns=['target'])
    y = df_train['target']

    # Remapear target a 0,1,2 para XGBoost (0=visitante, 1=empate, 2=local)
    y = y.replace({-1: 0, 0: 1, 1: 2})

    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)

    # RandomizedSearchCV con menos combinaciones y early stopping
    param_dist = {
        'n_estimators': [200, 300],
        'max_depth': [6, 8, 10],
        'learning_rate': [0.03, 0.05, 0.07],
        'subsample': [0.7, 0.8, 0.9],
        'colsample_bytree': [0.7, 0.8, 0.9]
    }

    # Creamos un modelo base con early stopping (usaremos validation_split)
    model = xgb.XGBClassifier(random_state=42, eval_metric='mlogloss',
                              early_stopping_rounds=10, validation_split=0.1)

    random_search = RandomizedSearchCV(model, param_distributions=param_dist,
                                       n_iter=20, cv=3, scoring='accuracy',
                                       n_jobs=-1, random_state=42, verbose=1)
    random_search.fit(X_scaled, y)

    best_model = random_search.best_estimator_
    print(f"📊 Mejores parámetros: {random_search.best_params_}")
    print(f"📊 Mejor precisión en validación cruzada: {random_search.best_score_:.2%}")

    # Evaluación en entrenamiento
    y_pred_train = best_model.predict(X_scaled)
    train_acc = accuracy_score(y, y_pred_train)
    print(f"📊 Precisión en entrenamiento: {train_acc:.2%}")

    # Guardar modelo y scaler para futuras ejecuciones
    joblib.dump(best_model, model_path)
    joblib.dump(scaler, scaler_path)
    print("✅ Modelo y scaler guardados en Drive.")

print("✅ Modelo XGBoost listo.")

# ============================================================
# 5. FUNCIÓN DE PREDICCIÓN (basada en probabilidades)
# ============================================================

def build_match_features(home, away):
    """Construye el vector de características para un partido (home vs away)"""
    s_h = stats[stats['Equipo'] == home]
    s_a = stats[stats['Equipo'] == away]
    if s_h.empty or s_a.empty:
        return None
    s_h = s_h.iloc[0]
    s_a = s_a.iloc[0]

    match = {}
    for col in stats.select_dtypes(include=[np.number]).columns:
        if col != 'Equipo':
            match[f"{col}_diff"] = s_h[col] - s_a[col]

    if 'ratio_goles_posesion' in stats.columns:
        match['ratio_goles_posesion_diff'] = s_h['ratio_goles_posesion'] - s_a['ratio_goles_posesion']
    if 'ratio_tarjetas' in stats.columns:
        match['ratio_tarjetas_diff'] = s_h['ratio_tarjetas'] - s_a['ratio_tarjetas']
    if 'eficiencia_gol' in stats.columns:
        match['eficiencia_gol_diff'] = s_h['eficiencia_gol'] - s_a['eficiencia_gol']
    if 'ratio_corners' in stats.columns:
        match['ratio_corners_diff'] = s_h['ratio_corners'] - s_a['ratio_corners']

    match['peso_local'] = 0.55  # ligera ventaja local en sede neutral
    return match

def predict_winner(home, away):
    """Predice el ganador de un partido y devuelve probabilidades y xG estimado."""
    match = build_match_features(home, away)
    if match is None:
        return None

    X_pred = pd.DataFrame([match])
    X_pred_scaled = scaler.transform(X_pred)
    probs = best_model.predict_proba(X_pred_scaled)[0]

    # Obtener las clases en orden original: [0,1,2] -> [-1,0,1]
    # best_model.classes_ debería ser [0,1,2]
    class_mapping = {label: idx for idx, label in enumerate(best_model.classes_)}
    p_home = probs[class_mapping[2]]  # original 1 (local)
    p_draw = probs[class_mapping[1]]  # original 0 (empate)
    p_away = probs[class_mapping[0]]  # original -1 (visitante)

    # Decisión por mayoría (probabilidad más alta)
    if p_home >= p_away and p_home >= p_draw:
        ganador = home
    elif p_away >= p_home and p_away >= p_draw:
        ganador = away
    else:
        ganador = home if p_home >= p_away else away

    # Estimación de xG
    s_h = stats[stats['Equipo'] == home].iloc[0] if not stats[stats['Equipo'] == home].empty else None
    s_a = stats[stats['Equipo'] == away].iloc[0] if not stats[stats['Equipo'] == away].empty else None
    avg_goals_home = s_h.get('avg_Goles_total', 1.2) if s_h is not None else 1.2
    avg_goals_away = s_a.get('avg_Goles_total', 1.2) if s_a is not None else 1.2
    xg_h = avg_goals_home * (0.8 + 0.4 * p_home)
    xg_a = avg_goals_away * (0.8 + 0.4 * p_away)

    return ganador, p_home, p_draw, p_away, xg_h, xg_a

# ============================================================
# 6. PREDECIR GANADORES DE OCTAVOS (CLASIFICADOS A CUARTOS)
# ============================================================

print("\n" + "="*80)
print("📊 PREDICCIONES - OCTAVOS DE FINAL (basadas en probabilidades)")
print("="*80 + "\n")

predicciones = []
clasificados = []

# Pre-cálculo de características para cada partido para reutilizar en simulación
partidos_features = []
for idx, row in cruces_octavos.iterrows():
    local = row['Equipo Local']
    visitante = row['Equipo Visitante']
    match_feat = build_match_features(local, visitante)
    if match_feat is None:
        print(f"⚠️ Datos insuficientes para {local} vs {visitante}. Se omite.")
        continue
    partidos_features.append((local, visitante, match_feat))

# Predicciones usando las características pre-calculadas
for local, visitante, match_feat in partidos_features:
    result = predict_winner(local, visitante)  # esta función reutiliza build, pero podemos optimizar más
    # Para evitar recalcular, podríamos adaptar predict_winner para aceptar match_feat ya calculado.
    # Pero por simplicidad, lo dejamos así; el costo es pequeño comparado con el entrenamiento.
    if result is None:
        continue
    ganador, p_h, p_d, p_a, xg_l, xg_v = result
    clasificados.append(ganador)
    predicciones.append({
        'Local': local,
        'Visitante': visitante,
        'Prob_Local': round(p_h, 3),
        'Prob_Empate': round(p_d, 3),
        'Prob_Visitante': round(p_a, 3),
        'xG_Local': round(xg_l, 2),
        'xG_Visitante': round(xg_v, 2),
        'Ganador': ganador
    })

df_pred = pd.DataFrame(predicciones)

print("📋 TABLA DE PREDICCIONES - OCTAVOS")
print(df_pred.to_string(index=False))
print("\n")

print("🎯 CLASIFICADOS A CUARTOS DE FINAL (según el modelo)")
for i, eq in enumerate(clasificados, 1):
    print(f"{i:2}. {eq}")

# ============================================================
# 7. SIMULACIÓN MONTE CARLO (1000 iteraciones para velocidad)
# ============================================================

print("\n🔄 Calculando porcentajes de clasificación a cuartos (1000 iteraciones Monte Carlo)...")

def simular_partido_con_features(match_feat, home, away):
    """Simula un partido usando las características ya calculadas"""
    X_pred = pd.DataFrame([match_feat])
    X_pred_scaled = scaler.transform(X_pred)
    probs = best_model.predict_proba(X_pred_scaled)[0]

    class_mapping = {label: idx for idx, label in enumerate(best_model.classes_)}
    p_home = probs[class_mapping[2]]
    p_away = probs[class_mapping[0]]

    # Simulación de goles con Poisson (lambda basado en promedios y probabilidades)
    s_h = stats[stats['Equipo'] == home].iloc[0] if not stats[stats['Equipo'] == home].empty else None
    s_a = stats[stats['Equipo'] == away].iloc[0] if not stats[stats['Equipo'] == away].empty else None
    avg_goals_home = s_h.get('avg_Goles_total', 1.2) if s_h is not None else 1.2
    avg_goals_away = s_a.get('avg_Goles_total', 1.2) if s_a is not None else 1.2
    lam_home = max(0.1, avg_goals_home + p_home * 1.5)
    lam_away = max(0.1, avg_goals_away + p_away * 1.5)
    g_h = np.random.poisson(lam_home)
    g_a = np.random.poisson(lam_away)

    if g_h > g_a:
        return home
    elif g_a > g_h:
        return away
    else:
        # Penales: ventaja ligeramente al equipo con mejor ranking
        # Obtener puntuaciones si existen
        rank_h = s_h.get('Puntuación', 1500) if s_h is not None else 1500
        rank_a = s_a.get('Puntuación', 1500) if s_a is not None else 1500
        prob_local_penal = 0.5 + (rank_h - rank_a) / 2000.0
        prob_local_penal = np.clip(prob_local_penal, 0.2, 0.8)
        return home if np.random.rand() < prob_local_penal else away

N_SIM = 1000
contador = defaultdict(int)

for _ in range(N_SIM):
    for local, visitante, match_feat in partidos_features:
        ganador = simular_partido_con_features(match_feat, local, visitante)
        if ganador:
            contador[ganador] += 1

total_sim = sum(contador.values())
if total_sim > 0:
    for eq in contador:
        contador[eq] = contador[eq] / total_sim

df_mc = pd.DataFrame(list(contador.items()), columns=['Equipo', 'Prob_Clasificacion_Cuartos'])
df_mc = df_mc.sort_values('Prob_Clasificacion_Cuartos', ascending=False)

print("\n📊 PORCENTAJES DE CLASIFICACIÓN A CUARTOS (Monte Carlo)")
print(df_mc.to_string(index=False))

# ============================================================
# 8. RESULTADOS FINALES
# ============================================================

print("\n" + "="*80)
print("RESULTADOS FINALES - CLASIFICADOS A CUARTOS DE FINAL")
print("="*80)

print("\n📌 CLASIFICADOS (por probabilidades)")
df_clas = pd.DataFrame({
    'Posición': range(1, len(clasificados)+1),
    'Equipo': clasificados
})
print(df_clas.to_string(index=False))

print("\n📌 TABLA DE PARTIDOS CON PROBABILIDADES Y xG")
print(df_pred.to_string(index=False))

if not df_mc.empty:
    print("\n📌 PROBABILIDADES DE CLASIFICACIÓN A CUARTOS (Monte Carlo)")
    print(df_mc.to_string(index=False))

print("\n✅ Análisis completado.")
print("   - Modelo: XGBoost con ajuste de hiperparámetros (RandomizedSearchCV)")
print("   - Características mejoradas con variables derivadas")
print("   - Decisión basada en la probabilidad más alta")
print("   - Validación cruzada para estimar precisión realista")
print("   - Simulación Monte Carlo: 1000 iteraciones para robustez (ajustable)")
print("   - Modelo guardado para reutilización en futuras ejecuciones")
print("\n⚠️ Nota: La precisión máxima realista en fútbol es ~66-70%. El modelo está optimizado para ese rango.")

"""# 🧠 Predicción de Clasificación a Cuartos de Final mediante Machine Learning

## 📌 Introducción

Este proyecto desarrolla un sistema predictivo para estimar qué equipos clasificarán a cuartos de final en una competición de fútbol, utilizando técnicas de **aprendizaje supervisado** mediante **XGBoost (eXtreme Gradient Boosting)** y una **simulación Monte Carlo** para modelar la incertidumbre inherente al deporte.

El sistema combina datos estadísticos, ingeniería de características y modelos probabilísticos para estimar resultados de partidos y probabilidades de clasificación.

---

## 🎯 Planteamiento del Problema

Sea un partido entre un equipo local ( i ) y un equipo visitante ( j ). Se define la variable objetivo:

$$
Y \in {0, 1, 2}
$$

donde:

* ( Y = 0 ): gana el visitante
* ( Y = 1 ): empate
* ( Y = 2 ): gana el local

El modelo estima la probabilidad condicional:

$$
P(Y = k \mid \mathbf{x}_{ij}), \quad k \in {0,1,2}
$$

donde ( \mathbf{x}_{ij} \in \mathbb{R}^d ) es el vector de características del partido.

---

## 📊 Representación Matemática de las Características

Cada partido se representa como la diferencia entre características del equipo local y visitante:

$$
\mathbf{x}_{ij} = \mathbf{x}_i - \mathbf{x}_j
$$

o componente a componente:

$$
x_m = f_{local,m} - f_{visitante,m}
$$

donde las variables incluyen:

* ranking FIFA
* valor de mercado
* goles promedio
* posesión
* remates a puerta
* córneres
* tarjetas
* faltas
* pases completados

---

## ⚙️ Ingeniería de Características

Se generan variables derivadas para capturar relaciones no lineales:

$$
\text{ratio}_{gp} = \frac{g}{\text{pos} + \epsilon}
$$

$$
\text{ratio}*{tarj} = \frac{t*{amarillas}}{faltas + \epsilon}
$$

$$
\text{eficiencia}_{gol} = \frac{g}{remates_puerta + \epsilon}
$$

$$
\text{ratio}_{corners} = \frac{corners}{\text{pos} + \epsilon}
$$

donde ( \epsilon = 0.01 ) evita divisiones por cero.

---

## 📏 Normalización de Variables

Se aplica estandarización tipo Z-score:

$$
z = \frac{x - \mu}{\sigma}
$$

donde:

* ( \mu ): media
* ( \sigma ): desviación estándar

Esto garantiza que todas las variables tengan media 0 y varianza 1.

---

## 🌳 Modelo XGBoost (Clasificación Multiclase)

El modelo predice probabilidades mediante la función softmax:

$$
P(Y = k \mid \mathbf{x}) = \frac{e^{s_k(\mathbf{x})}}{\sum_{k'=0}^{2} e^{s_{k'}(\mathbf{x})}}
$$

La predicción final es:

$$
\hat{y} = \arg\max_k P(Y = k \mid \mathbf{x})
$$

---

## ⚡ Función Objetivo

El modelo minimiza:

$$
\mathcal{L} = \sum_{i=1}^{N} \ell(y_i, \hat{y}*i) + \sum*{t=1}^{T} \Omega(f_t)
$$

donde la pérdida logarítmica es:

$$
\ell(y_i, \hat{y}_i) = -\log P(Y = y_i \mid \mathbf{x}_i)
$$

y la regularización:

$$
\Omega(f) = \gamma T + \frac{1}{2} \lambda \sum_{j=1}^{J} w_j^2
$$

---

## 🔁 Construcción del Modelo (Boosting)

El modelo se construye como:

$$
\hat{y}*i^{(t)} = \sum*{k=1}^{t} f_k(\mathbf{x}_i)
$$

En cada iteración se minimiza:

$$
\mathcal{L}^{(t)} \approx \sum_{i=1}^{N} \left[ g_i f_t(\mathbf{x}_i) + \frac{1}{2} h_i f_t(\mathbf{x}_i)^2 \right] + \Omega(f_t)
$$

donde:

* ( g_i ): gradiente
* ( h_i ): hessiano

---

## 📈 Evaluación del Modelo

### Accuracy

$$
\text{Accuracy} = \frac{1}{N} \sum_{i=1}^{N} \mathbb{I}(\hat{y}_i = y_i)
$$

### Log Loss

$$
\text{LogLoss} = -\frac{1}{N} \sum_{i=1}^{N} \log P(Y = y_i \mid \mathbf{x}_i)
$$

---

## 🎲 Simulación Monte Carlo (Clasificación a Cuartos)

Para estimar qué equipos avanzan a cuartos de final, se realizan ( N_{sim} = 1000 ) simulaciones.

### Modelado de goles (Poisson)

$$
G_h \sim \text{Poisson}(\lambda_h), \quad G_a \sim \text{Poisson}(\lambda_a)
$$

donde:

$$
\lambda_h = \max(0.1, \bar{g}_h + \alpha \cdot P(Y=2 \mid \mathbf{x}))
$$

$$
\lambda_a = \max(0.1, \bar{g}_a + \alpha \cdot P(Y=0 \mid \mathbf{x}))
$$

con ( \alpha = 1.5 ).

---

## ⚽ Resolución de Empates (Penales)

Si ( G_h = G_a ), el ganador se decide con:

$$
P_{penal} = \text{clip} \left( 0.5 + \frac{R_h - R_a}{2000}, , 0.2, , 0.8 \right)
$$

---

## 🏆 Probabilidad de Clasificación

La probabilidad de avanzar a cuartos se calcula como:

$$
P(\text{clasificación}) = \frac{1}{N_{sim}} \sum_{s=1}^{N_{sim}} \mathbb{I}(\text{equipo clasifica en simulación } s)
$$

---

## 🔄 Flujo del Sistema

1. Preprocesamiento de datos
2. Construcción del dataset
3. Ingeniería de características
4. Normalización
5. Entrenamiento con XGBoost
6. Predicción de partidos
7. Simulación Monte Carlo
8. Estimación de clasificados

---

## 📌 Conclusión

El sistema combina modelos de aprendizaje supervisado con simulaciones probabilísticas para estimar resultados de partidos y clasificaciones. Matemáticamente, integra:

* Modelos de probabilidad condicional
* Optimización basada en gradientes
* Distribuciones de Poisson
* Simulación Monte Carlo

Esto permite obtener estimaciones robustas en un entorno altamente incierto como el fútbol.

---

## 📚 Referencias

* Chen, T., & Guestrin, C. (2016). *XGBoost: A Scalable Tree Boosting System*.
* Friedman, J. (2001). *Gradient Boosting Machine*.
* Kuhn, M., & Johnson, K. (2013). *Applied Predictive Modeling*.

"""